version: '3.7'

services:
  auto:
    ports:
      - "7811:7860"  # Change the port assignment for the auto service to 7811
    environment:
      - CLI_ARGS=--xformers --enable-insecure-extension-access --theme dark --skip-torch-cuda-test --api
