x-base_service: &base_service
    ports:
      - "7860:7861"

services:
   auto:
     environment:
       - CLI_ARGS=--xformers --enable-insecure-extension-access --theme dark --skip-torch-cuda-test --api
